service: 'lami-accounts'

plugins:
  - serverless-dotenv-plugin 
  # - serverless-nest-monorepo

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs16.x

functions:
  auth:
    handler: dist/apps/auth/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
  lami-accounts:
    handler: dist/apps/lami-accounts/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'